
//post related actions
export const RECEIVE_ALL_POSTS = "RECEIVE_ALL_POSTS";
export const RECEIVE_POSTS_BY_CATEGORY = "RECEIVE_POSTS_BY_CATEGORY";
export const RECEIVE_POSTS_BY_ID = "RECEIVE_POSTS_BY_ID";
export const RECEIVE_POSTS_AFTER_NEW = "RECEIVE_POSTS_AFTER_NEW";
export const RECEIVE_POSTS_AFTER_UPDATE = "RECEIVE_POSTS_AFTER_UPDATE";
export const RECEIVE_VOTE_POSTS = "RECEIVE_VOTE_POSTS";
export const RECEIVE_POST_AFTER_DELETE = "RECEIVE_POST_AFTER_DELETE";


//comment related actions

export const RECEIVE_COMMENTS_BY_POSTID = "RECEIVE_COMMENTS_BY_POSTID";
export const RECEIVE_COMMENTS_AFTER_NEW = "RECEIVE_COMMENTS_AFTER_NEW";
export const RECEIVE_COMMENTS_AFTER_UPDATE = "RECEIVE_COMMENTS_AFTER_UPDATE";
export const RECEIVE_VOTE = "RECEIVE_VOTE";
export const RECEIVE_COMMENT_AFTER_DELETE = "RECEIVE_COMMENT_AFTER_DELETE";

//category realted actions
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
